name: Salesforce CI/CD - Validate against target org - ${{ github.event.pull_request.base.ref }}

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - qa
      - staging
      - prod
    paths:
      - "force-app/**"

jobs:
  validate-against-target-org:
    runs-on: ubuntu-latest

    environment: ${{ github.event.pull_request.base.ref }}

    env:
      TARGET_ALIAS: ${{ github.event.pull_request.base.ref }}-validate-pipeline
      TARGET_ORG_ID: ${{ secrets.TARGET_ORG_ID }}
      TARGET_ORG_AUTH_URL: ${{ secrets.TARGET_ORG_AUTH_URL }}

      TEMP_MANIFEST: "tempDeployManifest.xml"
      DEPLOY_WAIT: 10
      VALIDATED_JOB_ID: ""
      SOURCE_DIR: "force-app"

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.1"
          cache: "npm"

      # 3. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          echo "Validating PR merge from source branch: ${{ github.event.pull_request.head.ref }} to target branch: ${{ github.event.pull_request.base.ref }}"
          sudo npm install @salesforce/cli@2.128.5 --global
          sf --version

      #4. Run LWC tests
      - name: Run LWC tests
        run: |
          npm ci

          set -o pipefail
          npx lwc-jest 2>&1
          LWC_EXIT_CODE=$?

          echo "LWC_EXIT_CODE: $LWC_EXIT_CODE"

          if [ $LWC_EXIT_CODE -ne 0 ]; then
              echo "❌ LWC tests failed"
              exit $LWC_EXIT_CODE
          fi

          echo "✅ LWC tests passed"

      # 5. Authenticate to Target Org
      - name: Authenticate to Target Org
        run: |
          AUTH_FILE=$(mktemp)
          echo "$TARGET_ORG_AUTH_URL" > "$AUTH_FILE"
          echo "TARGET_ORG_AUTH_URL: $TARGET_ORG_AUTH_URL"

          sf org login sfdx-url --sfdx-url-file "$AUTH_FILE" --alias "$TARGET_ALIAS"
          rm "$AUTH_FILE"          

           ACTUAL_ORG_ID=$(sf org display --target-org "$TARGET_ALIAS" --json | node -pe "JSON.parse(fs.readFileSync(0)).result.id")

          if [ "${ACTUAL_ORG_ID:0:15}" != "${TARGET_ORG_ID:0:15}" ]; then
              echo "--- Authentication failed. Exiting script. ---"
              exit 1
          fi

      # 6. Generate Manifest file
      - name: Generate Manifest file
        run: |
          sf project generate manifest --source-dir "$SOURCE_DIR" --name "$TEMP_MANIFEST"

      # 7. Authenticate and deploy metadata to Target org
      - name: Validate Metadata against Target Org
        run: |

          DEPLOY_JSON=$(sf project deploy validate \
            --manifest "$TEMP_MANIFEST" \
            --target-org "$TARGET_ALIAS" \
            --test-level RunLocalTests \
            --wait "$DEPLOY_WAIT" \
            --json || true)

          STATUS=$(echo "$DEPLOY_JSON" | node -pe "
              const j = JSON.parse(require('fs').readFileSync(0));
              j.result?.status || 'Unknown';
          ")

          if [[ $STATUS != "Succeeded" ]]; then
              echo "❌ Deployment failed! Status: $STATUS"
              echo "DEPLOY RESPONSE JSON: $DEPLOY_JSON"
              exit $EXIT_CODE
          fi

          echo "✅ Validation Status: $STATUS"

          echo "🎉 Validation pipeline completed successfully!"

      # 8. Cleanup
      - name: Cleanup
        if: always()
        run: |
          echo "🔹 Cleaning up: Logging out from $TARGET_ALIAS..."
          sf org logout --target-org "$TARGET_ALIAS" --no-prompt || true

          echo "🔹 Cleaning up: Deleting temporary manifest file..."
          [[ -f "$TEMP_MANIFEST" ]] && rm -f "$TEMP_MANIFEST"

          echo "✅ Cleanup complete"
