name: Salesforce CI/CD - Validate against scratch org

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
    paths:
      - "force-app/**"

run-name: Validate against scratch org - ${{ github.event.pull_request.head.ref }}

jobs:
  validate-against-scratch-org:
    name: Validate against scratch org - ${{ github.event.pull_request.head.ref }}
    runs-on: ubuntu-latest

    env:
      DEV_HUB_ORG_ID: ${{ secrets.DEV_HUB_ORG_ID }}
      DEV_HUB_AUTH_URL: ${{ secrets.DEV_HUB_AUTH_URL }}

      DEV_HUB_TARGET_ALIAS: ${{ github.event.pull_request.head.ref }}-scratch-validate-pipeline

      SCRATCH_ORG_ALIAS: ${{ github.event.pull_request.head.ref }}-scratch-validate
      SCRATCH_ORG_DEFINITION: "./config/scratch-org-def.json"
      SOURCE_DIR: "force-app"

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          echo "Validating PR merge from source branch: ${{ github.event.pull_request.head.ref }} to target branch: ${{ github.event.pull_request.base.ref }}"
          sudo npm install @salesforce/cli --global
          sf --version

      # 4. Run LWC tests
      - name: Run LWC tests
        run: |
          echo "--- Running LWC tests ---"

          npm ci
          set -o pipefail
          npx lwc-jest -- --passWithNoTests 2>&1
          LWC_EXIT_CODE=$?

          if [ $LWC_EXIT_CODE -ne 0 ]; then
              echo "❌ LWC tests failed"
              exit $LWC_EXIT_CODE
          fi

          echo "--- ✅ All LWC tests passed ---"
          echo "✅ Validation and Deployment Complete!"

      # 5. Authenticate to Dev Hub
      - name: Authenticate to Dev Hub
        uses: ./.github/actions/authorize-org-with-auth-url
        with:
          target-org-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}
          target-org-alias: ${{ env.DEV_HUB_TARGET_ALIAS }}
          expected-org-id: ${{ secrets.DEV_HUB_ORG_ID }}

      # 6. Create scratch org for validation/testing
      - name: Create Scratch Org
        run: |

          echo "Adding Dev Hub Org ID to Scratch Org Definition..."
          TMP_SCRATCH_ORG_DEF=$(mktemp)        

          node -e "
            const fs = require('fs'); 
            const srcPath = 'config/scratch-org-def.json'; 
            const tmp = '$TMP_SCRATCH_ORG_DEF'; 
            const j = JSON.parse(fs.readFileSync(srcPath,'utf8')); 
            j.sourceOrg = process.env.DEV_HUB_ORG_ID; 
            fs.writeFileSync(tmp, JSON.stringify(j,null,2));
          " > "$TMP_SCRATCH_ORG_DEF"

          echo "Creating Scratch Org..."          
          CREATE_SCRATCH_ORG_JSON=$(
              sf org create scratch \
                  --definition-file "$TMP_SCRATCH_ORG_DEF" \
                  --target-dev-hub "$DEV_HUB_TARGET_ALIAS" \
                  --alias "$SCRATCH_ORG_ALIAS" \
                  --set-default \
                  --duration-days 1 \
                  --wait 10 \
                  --json
          )

          echo "$CREATE_SCRATCH_ORG_JSON"

          SCRATCH_ORG_STATUS=$(echo "$CREATE_SCRATCH_ORG_JSON" | node -pe "
              const j = JSON.parse(require('fs').readFileSync(0));
              j.status ?? 1;           
          ")

          echo "SCRATCH_ORG_STATUS: $SCRATCH_ORG_STATUS"

          if [ $SCRATCH_ORG_STATUS -ne 0 ]; then
              echo "--- Scratch org creation failed. Exiting script. ---"
              exit 1
          fi

          echo "✅ Scratch org created successfully"

      # 7. Deploy Metadata to Scratch Org
      - name: Deploy Metadata to Scratch Org
        run: |
          echo "🔹 Deploying to Scratch org '$SCRATCH_ORG_ALIAS'..."

          sf project deploy start --target-org $SCRATCH_ORG_ALIAS --source-dir force-app --wait 10

      # 8. Run Apex tests
      - name: Run Apex tests
        run: |
          echo "--- Running Apex tests ---"
          sf apex run test -o $SCRATCH_ORG_ALIAS --wait 10 -y --result-format json --synchronous > test-results.json || true

          APEX_TESTS_SUCCESS=$(node -e "console.log(JSON.parse(require('fs').readFileSync('test-results.json')).result.summary.outcome)")

          echo "APEX TESTS_SUCCESS: $APEX_TESTS_SUCCESS"
                
          if [ "$APEX_TESTS_SUCCESS" != "Passed" ]; then
              echo "--- Apex Tests failed. Exiting script. ---"
              exit 1
          fi

          echo "--- All Apex tests passed ---"

          echo "🎉 Deployment pipeline completed successfully!"

      # 9. Cleanup
      - name: Cleanup
        if: always()
        run: |
          echo "🔹 Cleaning up: Deleting scratch org: $SCRATCH_ORG_ALIAS..."
          sf org delete scratch --target-org "$SCRATCH_ORG_ALIAS" --no-prompt

          echo "🔹 Cleaning up: Logging out from Dev Hub: $DEV_HUB_TARGET_ALIAS..."
          sf org logout --target-org "$DEV_HUB_TARGET_ALIAS" --no-prompt || true        

          echo "🔹 Cleaning up: Deleting apex test results..."
          rm -f -v test-results.json

          echo "✅ Cleanup complete"
